### ISSUE TITLE
getting blank screen instead of actual video in grid demo

### ISSUE THREAD

**Issue by Awais-cb** [daily-co/daily-demos#10]
I am unable to run the grid demo due to this issue can't see the video either from my side or participant's side.

**Comment by kimberleejohnson** [comment]
Hi, @Awais-cb! I fiddled with this demo recently, and I might be able to help. 

Could you please tell me a bit more about the issues you were running into? Information like your browser, operating system, and any error messages you're seeing in the console would be helpful.

**Comment by kimberleejohnson** [comment]
Hi, @Awais-cb! 

Another follow up here: 

Is the issue that you are able to see only one video when you start the demo? For example, when you try to open the call link in a new tab, you're not able to see the second participant's actual video? 

If that's the case, hard-coding a meeting link, instead of using one of the generated demo links, would solve the issue. But, if it's something else that you're experiencing, please let me know and I will do what I can to help. 

Thank you!
Kimberlee

**Comment by kimberleejohnson** [comment]
We're going to go ahead and close this out, but if there's anything else we can help with please reach out at `help@daily.co`. Thank you!
