### ISSUE TITLE
watermark in the video 

### ISSUE THREAD

**Issue by sandys** [daily-co/daily-demos#24]
is it possible to inject a watermark into the video ? 

like this example of twilio - https://www.twilio.com/blog/add-an-overlay-to-web-video-chat

**Comment by kimberleejohnson** [comment]
Hi, @sandys! First of all, apologies for our delay here. If you ever have an urgent question, feel free to write help@daily.co, or you can reach me at kimberlee@daily.co. 

Thanks for sharing that example. Yes, it's possible to do this on Daily calls. Experimenting with our react-demo, I prototyped this by doing a few things: 

* I added a useEffect hook for a new function called addOverlay, so the function only runs once on each load. 
* That function grabs all of the elements by class name "tile small". 
* Created a new element that I could append to those elements.
* Then converted those elements into an Array using Array.from, so that I could iterate over and add a name for each. 

Sample code below! Again, this was a very quick prototype, and there are many more things that could be done to make it better and more specific to your app, like styling the name overlay and making sure the name overlay matches the name of the meeting participants. 

I hope this is a good starting point, and please let me know of any more questions. 

Thank you! 
Kimberlee 

```javascript 
useEffect(() => {
    function addOverlay() {
      const videoContainers = document.getElementsByClassName("tile small"); 
      const overlay = document.createElement("p"); 
      overlay.classList.add("name"); 
      overlay.append(document.createTextNode("Your name"));
      Array.from(videoContainers).forEach(container => container.append(overlay)); 
    }
    addOverlay(); 
  }, [])
```

**Comment by kimberleejohnson** [comment]
I'm going to go ahead and close this issue since it's been a minute, but we also added a tutorial for this to the backlog.
