### ISSUE TITLE
[DEMO-REQUEST] Demo for the version you guys have as default?

### ISSUE THREAD

**Issue by truuth-of-abhi** [daily-co/daily-demos#38]
# Demo request 

Can you please add the demo which you guys use for the iframe? 

# Why you need this 

The demos in this repo are for local, but how can I get the same layout the remote person gets. That's what I want and is quite good, any documentation for that?

# Alternatives you've considered

A flexbox and css grid template.

**Comment by kimberleejohnson** [comment]
Hi, @truuth-of-abhi! Thanks so much for asking this. 

It sounds like what you're looking for is how to set the Daily video chat interface fullscreen, instead of seeing it just in the corner like it is in [simple-demo](https://github.com/daily-co/daily-demos/blob/main/static-demos/simple-demo/simple.html). 

To do that,  all you have to do is, in the simple.html code: 
- Comment out line 33 
- Paste the following code after that 

```html 
callFrame = window.DailyIframe.createFrame({
          showLeaveButton: true,
          iframeStyle: {
            width: '100%',
            height: '100%',
          },
        });
```

I'll be sure to add a new demo that illustrates this as soon as I can, too, but I wanted to share this code now in case helpful. Let me know if there is anything else I can help with in the meantime? Thank you!

**Comment by kimberleejohnson** [comment]
I'm still working on this, @truuth-of-abhi, but I've got a branch up now that might be useful: https://github.com/daily-co/daily-demos/blob/feat/demo-fullscreen-prebuiltUI/static-demos/fullscreen-prebuilt-UI/fullscreen-prebuilt-ui.html 

I'll hope to merge this into main in the next few days, and please let me know if there is more I can do. Thanks again!

**Comment by truuth-of-abhi** [comment]
What I mean't was how do you achieve this grid in your production app?
![image](https://user-images.githubusercontent.com/66814547/94221012-e7617800-ff07-11ea-88ad-4d176cb84132.png)

**Comment by truuth-of-abhi** [comment]
@kimberleejohnson

**Comment by truuth-of-abhi** [comment]
Code for how you guys do this?
![image](https://user-images.githubusercontent.com/66814547/94276786-5372c900-ff66-11ea-9360-8fd8cbb4b183.png)

**Comment by philmillman** [comment]
hello @truuth-of-abhi if you have product specific questions, please send them to help@daily.co or reach out via the chat on the website.
